openapi: "3.0.0"
info:
  version: 1.0.0
  title: Battery Archive API
paths:
  /cells:
    get:
      summary: Fetches all Cells
      x-openapi-router-controller: app.api.controllers.cell_controller
      operationId: get_cells
      tags:
        - cells
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of cells
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Cells"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cell:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        tag:
          type: string
    Cells:
      type: array
      items:
        $ref: "#/components/schemas/Cell"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
