openapi: 3.0.0
info:
  title: Battery Archive API
  description: An API to access Battery Archive Information
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /cells:
    get:
      summary: Returns a list of all cells and their respective metadata
      operationId: getAllCells
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: Creates a new cell with metadata in Archive
      operationId: createCell

      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: integer
                format: int64
  /cells/{cellId}:
    get:
      summary: Returns a single cell with metadata
      operationId: getCell
      parameters:
        - name: cellId
          in: path
          required: true
          description: The id of the cell to retrieve
          schema:
            type: string
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cell"
    patch:
      summary: Update the metadata of a single cell
      operationId: updateCell  
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    delete:
      summary: Deletes a single cell 
      operationId: deleteCell 
      responses:
        '200':    # status code

  /cells/{cellId}/tests/{testName}:
    get:
      summary: Returns all data for test named testName on cellId in Archive
      description: 
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
    post:
      summary: - Creates new test named testName for cellId in Archive
      description: 
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string   
components:
  schemas:
    Cell:
      type: object
      required:
        - id
        - name
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
        tag:
          type: string
    Cells:
      type: array
      items:
        $ref: "#/components/schemas/Cell"               