openapi: 3.0.0
info:
  title: Battery Archive API
  description: An API to access Battery Archive Information
  version: 0.0.1
servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing
paths:
  /cells:
    get:
      summary: Returns a list of all cells and their respective metadata
      description: 
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /cells/{id}:
    get:
      summary: Returns a single cell with metadata
      description: 
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string
  /cells/{id}/data:
    get:
      summary: Returns cell with metadata and timeseries data
      description: 
      responses:
        '200':    # status code
          description: A JSON array of cells
          content:
            application/json:
              schema: 
                type: array
                items: 
                  type: string