openapi: "3.0.0"
info:
  version: 1.0.0
  title: Battery Archive API
  license:
    name: MIT
paths:
  /cells:
    get:
      summary: List all Cells
      operationId: listCells
      tags:
        - cells
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of cells
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Cells"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a Cell
      operationId: createCells
      tags:
        - cells
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cells/{cellId}:
    get:
      summary: Info for a specific Cell
      operationId: showCellById
      tags:
        - cells
      parameters:
        - name: cellId
          in: path
          required: true
          description: The id of the cell to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Cell"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /cells/{cellId}/tests:
    get:
      summary: Info for all Tests on Cell
      operationId: showTestsForCellById
      tags:
        - tests
      parameters:
        - name: cellId
          in: path
          required: true
          description: The id of the cell to retrieve
          schema:
            type: string
      responses:
        '200':
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Tests"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a test for Cell
      operationId: createTest
      tags:
        - tests
      parameters:
        - name: cellId
          in: path
          required: true
          description: The id of the cell to retrieve
          schema:
            type: string
      responses:
        '201':
          description: Null response
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /tests:
    get:
      summary: List all Tests
      operationId: listTests
      tags:
        - tests
      parameters:
        - name: limit
          in: query
          description: How many items to return at one time (max 100)
          required: false
          schema:
            type: integer
            format: int32
      responses:
        '200':
          description: A paged array of cells
          headers:
            x-next:
              description: A link to the next page of responses
              schema:
                type: string
          content:
            application/json:    
              schema:
                $ref: "#/components/schemas/Tests"
        default:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
components:
  schemas:
    Cell:
      type: object
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
        tag:
          type: string
    Cells:
      type: array
      items:
        $ref: "#/components/schemas/Cell"
    Error:
      type: object
      required:
        - code
        - message
      properties:
        code:
          type: integer
          format: int32
        message:
          type: string
    Test:
      type: object
      required:
        - name
      properties:
        name:
          type: string
        tag:
          type: string
    Tests:
      type: array
      items:
        $ref: "#/components/schemas/Test"
