openapi: "3.0.0"
info:
  version: 1.0.0
  title: Battery Archive API
paths:
  # /:
  #   get:
  #     summary: Test
  #     x-openapi-router-controller: app.controllers.auth_controller
  #     operationId: health_check
  #     tags:
  #       - Auth
  #     responses:
  #       "200":
  #         description: Successfull response
  /login:
    post:
      summary: Login
      x-openapi-router-controller: app.controllers.auth_controller
      operationId: login
      tags:
        - Auth
      responses:
        "200":
          description: Successfull response
  /logout:
    get:
      summary: Logout
      x-openapi-router-controller: app.controllers.auth_controller
      operationId: logout
      tags:
        - Auth
      responses:
        "200":
          description: Successfull response
  /cells/{test}/meta:
    get:
      summary: Fetches metadata for all cells
      x-openapi-router-controller: app.controllers.cell_metadata_controller
      operationId: get_cells
      tags:
        - Cell Meta
      parameters:
        - name: test
          in: path
          description: test type
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successfull
  /cells/{cell_id}:
    delete:
      summary: Delete a cell from archive
      x-openapi-router-controller: app.controllers.cell_metadata_controller
      operationId: delete_cell
      tags:
        - Cell Meta
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successfull
  /upload/cells/{tester}:
    post:
      summary: Upload cycle test file
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: upload_file
      parameters:
        - name: tester
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Upload
      responses:
        "200":
          description: Successfull response
  /upload/cells/initialize:
    post:
      summary: Upload cycle test file
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: init_file_upload
      # parameters:
      #   - name: tester
      #     in: path
      #     description: Cell ID of the resource to get
      #     required: true
      #     style: simple
      #     explode: false
      #     schema:
      #       type: string
      tags:
        - Upload
      responses:
        "200":
          description: Successfull response
  /upload/cells/status/{cell_id}:
    get:
      summary: Check upload status
      x-openapi-router-controller: app.controllers.status_check_controller
      operationId: get_status
      parameters:
        - name: cell_id
          in: path
          description: Cell ID
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Upload
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_timeseries/{cell_id}:
    get:
      summary: Download Cycle timeseries
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: download_cycle_timeseries
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_data/{cell_id}:
    get:
      summary: Download cycle data
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: download_cycle_data
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
  /echarts/cycleQuantitiesByStep:
    get:
      summary: Fetches cycle quantities by step query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_cycle_quantities_by_step
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
        - name: step
          in: query
          description: steps
          explode: true
          required: true
          style: form
          schema:
            type: integer
            items:
              type: integer
      responses:
        "200":
          description: Successfull response
  /echarts/energyAndCapacityDecay:
    get:
      summary: Fetches energy and capacity decay query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_energy_and_capacity_decay
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successfull response
  /echarts/efficiency:
    get:
      summary: Fetches efficiency query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_efficiency
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successfull response
  /echarts/compareByCycleTime:
    get:
      summary: Fetches comapre cycle voltage and current query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_compare_by_cycle_time
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successfull response
  /echarts/forceAndDisplacement:
    get:
      summary: Fetches force and displacement query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_force_and_displacement
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
        - name: sample
          in: query
          description: sample
          explode: true
          required: true
          style: form
          schema:
            type: integer
            items:
              type: integer
      responses:
        "200":
          description: Successfull response
  /echarts/testTempratures:
    get:
      summary: Fetches test tempratures query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_test_tempratures
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
        - name: sample
          in: query
          description: sample
          explode: true
          required: true
          style: form
          schema:
            type: integer
            items:
              type: integer
      responses:
        "200":
          description: Successfull response
  /echarts/voltage:
    get:
      summary: Fetches voltage query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_voltage
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
        - name: sample
          in: query
          description: sample
          explode: true
          required: true
          style: form
          schema:
            type: integer
            items:
              type: integer
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_data_json/{cell_id}:
    get:
      summary: Download cycle timeseries
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: get_cycle_data_json
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_timeseries_json/{cell_id}:
    get:
      summary: Download cycle timeseries
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: get_cycle_timeseries_json
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
