openapi: "3.0.0"
info:
  version: 1.0.0
  title: Battery Archive API
paths:
  /login:
    post:
      summary: Login
      x-openapi-router-controller: app.controllers.auth_controller
      operationId: login
      tags:
        - Auth
      responses:
        "200":
          description: Successfull response
  /logout:
    get:
      summary: Logout
      x-openapi-router-controller: app.controllers.auth_controller
      operationId: logout
      tags:
        - Auth
      responses:
        "200":
          description: Successfull response
  /cells/all/meta:
    get:
      summary: Fetches metadata for all cells
      x-openapi-router-controller: app.controllers.cell_metadata_controller
      operationId: get_cells
      tags:
        - Cell Meta
      responses:
        "200":
          description: Successfull
  /cells/{cell_id}:
    delete:
      summary: Delete a cell from archive
      x-openapi-router-controller: app.controllers.cell_metadata_controller
      operationId: delete_cell
      tags:
        - Cell Meta
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to delete
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        "200":
          description: Successfull
  /upload/cells/{tester}:
    post:
      summary: Upload cycle test file
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: upload_file
      parameters:
        - name: tester
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Upload
      responses:
        "200":
          description: Successfull response
  /upload/cells/status:
    get:
      summary: Check upload status
      x-openapi-router-controller: app.controllers.status_check_controller
      operationId: get_status
      tags:
        - Upload
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_timeseries/{cell_id}:
    get:
      summary: Download Cycle data
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: download_cycle_timeseries
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
  /download/cells/cycle_data/{cell_id}:
    get:
      summary: Download cycle timeseries
      x-openapi-router-controller: app.controllers.file_transfer_controller
      operationId: download_cycle_data
      parameters:
        - name: cell_id
          in: path
          description: Cell ID of the resource to get
          required: true
          style: simple
          explode: false
          schema:
            type: string
      tags:
        - Download
      responses:
        "200":
          description: Successfull response
  /echarts/cycleQuantitiesByStep:
    get:
      summary: Fetches cycle quantities by step query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_cycle_quantities_by_step
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
        - name: step
          in: query
          description: steps
          explode: true
          required: true
          style: form
          schema:
            type: integer
            items:
              type: integer
      responses:
        "200":
          description: Successfull response
  /echarts/energyAndCapacityDecay:
    get:
      summary: Fetches energy and capacity decay query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_energy_and_capacity_decay
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successfull response
  /echarts/efficiency:
    get:
      summary: Fetches efficiency query results
      x-openapi-router-controller: app.controllers.echarts_controller
      operationId: get_efficiency
      tags:
        - Echart
      parameters:
        - name: cell_id
          in: query
          description: Cell ID
          explode: true
          required: true
          style: form
          schema:
            type: array
            items:
              type: string
      responses:
        "200":
          description: Successfull response
